### ISSUE TITLE
Error: window is not defined

### ISSUE THREAD

**Issue by AmenRa666** [pushtell/react-bootstrap-date-picker#10]
Hello, I got this error, any ideas?
```
/Users/Elias/noteshare/node_modules/react-bootstrap-date-picker/lib/index.js:189
    var language = (window.navigator.userLanguage || window.navigator.language || '').toLowerCase();
                    ^

ReferenceError: window is not defined
    at Function.getDefaultProps (/Users/Elias/noteshare/node_modules/react-bootstrap-date-picker/lib/index.js:189:21)
    at Object.ReactClass.createClass (/Users/Elias/noteshare/node_modules/react/lib/ReactClass.js:682:46)
    at Object.<anonymous> (/Users/Elias/noteshare/node_modules/react-bootstrap-date-picker/lib/index.js:173:35)
    at Module._compile (module.js:409:26)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/Elias/noteshare/node_modules/node-jsx/index.js:29:12)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/Elias/noteshare/ui/common/topbar/uploadButton.jsx:17:18)
```

**Comment by AmenRa666** [comment]
Can the problem be the server-side rendering?

**Comment by huzzbuzz** [comment]
I get the same errors
